[book]
authors = ["HoraeDB Authors"]
language = "en"
multilingual = true
src = "src"
title = "HoraeDB Documentation"

[build]
use-default-preprocessors = false

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/apache/incubator-horaedb"
edit-url-template = "https://github.com/apache/incubator-horaedb-docs/edit/main/docs/{path}"
additional-css = ["style.css"]
additional-js = ["sidebar.js"]

[output.html.fold]
enable = true
