[book]
authors = ["HoraeDB Authors"]
language = "en"
multilingual = true
src = "src/en"
title = "HoraeDB Documentation"

[build]
use-default-preprocessors = false

[preprocessor.links]

[[output.i18n.translations]]
src = "src/cn"
language = "cn"
translators = ["HoraeDB Authors"]
title = "HoraeDB 文档"

[output.random]
command = "/bin/bash ../../move.sh"

[output.html]
git-repository-url = "https://github.com/apache/incubator-horaedb"
edit-url-template = "https://github.com/apache/incubator-horaedb-docs/edit/main/docs/{path}"
additional-css = ["style.css"]
additional-js = ["sidebar.js"]

[output.html.fold]
enable = true
