[node]
addr = "127.0.0.1"

[server]
bind_addr = "0.0.0.0"
http_port = 5441
grpc_port = 8832
mysql_port = 13307

[logger]
level = "info"

[analytic.storage]
mem_cache_capacity = '1G'
mem_cache_partition_bits = 0

[analytic.storage.object_store]
type = "Local"
data_dir = "/tmp/horaedb1"

[analytic.wal]
type = "RocksDB"
data_dir = "/tmp/horaedb1"

[cluster_deployment]
mode = "WithMeta"
cmd_channel_buffer_size = 10

[cluster_deployment.meta_client]
cluster_name = "defaultCluster"
meta_addr = "http://127.0.0.1:2379"
lease = "10s"
timeout = "5s"

[cluster_deployment.etcd_client]
server_addrs = ['127.0.0.1:2379']

[limiter]
write_block_list = ['mytable1']
read_block_list = ['mytable1']
