# Note that the config needs parameters replacement before use, including:
# - HoraeMeta addr;
# - Parameters of Aliyun OSS;
# - Paramsters of the OBKV cluster;
#
# And one thing deserves explanation that this config is used for running horaedb docker container:
# ```
# docker run -d --name horaedb-server \
# -v /etc/horaedb/horaedb.toml:{path_to_this_config} \
# horaedb/horaedb-server
# ```

[server]
bind_addr = "0.0.0.0"
http_port = 5440
grpc_port = 8831

[logger]
level = "info"

[tracing]
dir = "/home/admin/data/horaedb"

[runtime]
read_thread_num = 20
write_thread_num = 16
background_thread_num = 12

[cluster_delpoyment]
mode = "WithMeta"

[cluster_deployment.meta_client]
cluster_name = "defaultCluster"
meta_addr = "http://{HoraeMetaAddr}:2379"
lease = "10s"
timeout = "5s"

[cluster_deployment.etcd_client]
server_addrs = ['{HoraeMetaAddr}:2379']

[analytic]
write_group_worker_num = 16
replay_batch_size = 100
max_replay_tables_per_batch = 128
write_group_command_channel_cap = 1024
sst_background_read_parallelism = 8

[analytic.manifest]
scan_batch_size = 100
snapshot_every_n_updates = 10000
scan_timeout = "5s"
store_timeout = "5s"

[analytic.wal]
type = "Obkv"

[analytic.wal.data_namespace]
ttl = "365d"

[analytic.wal.obkv]
full_user_name = "{FullUserName}"
param_url = "{ParamUrl}"
password = "{Password}"

[analytic.wal.obkv.client]
sys_user_name = "{SysUserName}"
sys_password = "{SysPassword}"

[analytic.storage]
mem_cache_capacity = "20GB"
# 1<<8=256
mem_cache_partition_bits = 8

[analytic.storage.object_store]
type = "Aliyun"
key_id = "key_id"
key_secret = "key_secret"
endpoint = "endpoint"
bucket = "bucket"
prefix = "data_dir"

[analytic.table_opts]
arena_block_size = 2097152
write_buffer_size = 33554432

[analytic.compaction]
schedule_channel_len = 16
schedule_interval = "30m"
max_ongoing_tasks = 8
memory_limit = "4G"