name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "**.md"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prettier check
        run: |
          # if you encounter error, rerun the command below and commit the changes
          make lint
          git diff --exit-code
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          npm i -D postcss postcss-cli autoprefixer
          hugo --minify
